# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17-9tLfdnUpyGVqRjinZAUqqv9dnKhV1V
"""

import streamlit as st
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import datetime
import time

# --- SETUP PAGE CONFIG ---
st.set_page_config(page_title="Bible Character Quiz", page_icon="📖")

# --- CONNECT TO GOOGLE SHEETS ---
# We use st.cache_resource so we don't reconnect every time the user clicks a button
@st.cache_resource
def connect_to_sheet():
    # In Streamlit Cloud, we use st.secrets. locally we can use a try/except block.
    try:
        # Load from Streamlit Secrets (Production)
        creds_dict = dict(st.secrets["gcp_service_account"])
        creds = ServiceAccountCredentials.from_json_keyfile_dict(creds_dict, ["https://spreadsheets.google.com/feeds", "https://www.googleapis.com/auth/drive"])
    except FileNotFoundError:
        # Load from local file (Development)
        scope = ["https://spreadsheets.google.com/feeds", "https://www.googleapis.com/auth/drive"]
        creds = ServiceAccountCredentials.from_json_keyfile_name("credentials.json", scope)

    client = gspread.authorize(creds)
    return client.open("Bible Character Game  - Python")

# --- INITIALIZE SESSION STATE ---
if 'page' not in st.session_state:
    st.session_state.page = 'home'
if 'score' not in st.session_state:
    st.session_state.score = 0
if 'user_email' not in st.session_state:
    st.session_state.user_email = ""
# Mode 1 Specifics
if 'm1_answers' not in st.session_state:
    st.session_state.m1_answers = []
# Mode 2 Specifics
if 'm2_index' not in st.session_state:
    st.session_state.m2_index = 0
if 'm2_attempts' not in st.session_state:
    st.session_state.m2_attempts = 0

# --- FUNCTIONS ---

def save_mode1_session(sheet, category_id, score, answers):
    session_sheet = sheet.worksheet("Mode1_Sessions")
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    session_id = f"SESS-{int(time.time())}"
    row_data = [session_id, category_id, st.session_state.user_email, timestamp, score] + answers
    session_sheet.append_row(row_data)

def save_mode2_guess(sheet, char_id, attempts, solved, guess):
    session_sheet = sheet.worksheet("Mode2_Sessions")
    guess_id = f"GUESS-{int(time.time())}-{char_id}"
    row_data = [guess_id, char_id, st.session_state.user_email, attempts, str(solved).upper(), guess]
    session_sheet.append_row(row_data)

# --- PAGES ---

def home_page():
    st.title("📖 Bible Character Quiz")
    st.write("Welcome! Please enter your email to start tracking your score.")

    email = st.text_input("Email Address")

    if st.button("Start Game"):
        if email:
            st.session_state.user_email = email
            st.session_state.page = 'menu'
            st.rerun()
        else:
            st.error("Please enter an email.")

def menu_page():
    st.title(f"Welcome, {st.session_state.user_email}")
    st.write(f"**Current Score:** {st.session_state.score}")

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Mode 1: Categories")
        st.write("List all items in a category (e.g., The 12 Apostles).")
        if st.button("Play Category Mode"):
            st.session_state.page = 'mode1_select'
            st.rerun()

    with col2:
        st.subheader("Mode 2: Characters")
        st.write("Guess the character from clues.")
        if st.button("Play Character Mode"):
            st.session_state.page = 'mode2_play'
            st.session_state.m2_index = 0 # Reset index
            st.rerun()

def mode1_select(sheet):
    st.title("Select a Category")
    cat_sheet = sheet.worksheet("1-Category")
    categories = cat_sheet.get_all_records()

    # Create a nice list for the dropdown
    cat_options = [f"{c['CategoryName']} (Needs {c['TotalRequired']})" for c in categories]
    selected_option = st.selectbox("Choose a category:", cat_options)

    if st.button("Start Category"):
        # Find the actual category object based on selection
        index = cat_options.index(selected_option)
        st.session_state.current_category = categories[index]
        st.session_state.m1_answers = [] # Reset answers
        st.session_state.page = 'mode1_play'
        st.rerun()

    if st.button("Back to Menu"):
        st.session_state.page = 'menu'
        st.rerun()

def mode1_play(sheet):
    cat = st.session_state.current_category
    st.title(f"Category: {cat['CategoryName']}")
    st.info(f"Please name {cat['TotalRequired']} items.")

    # Progress
    st.progress(len(st.session_state.m1_answers) / cat['TotalRequired'])
    st.write(f"Found: {len(st.session_state.m1_answers)} / {cat['TotalRequired']}")

    # Show valid answers so far
    for ans in st.session_state.m1_answers:
        st.success(f"✅ {ans}")

    # Input Logic
    if len(st.session_state.m1_answers) < cat['TotalRequired']:
        with st.form("ans_form", clear_on_submit=True):
            user_input = st.text_input("Enter an answer:")
            submitted = st.form_submit_button("Submit")

            if submitted and user_input:
                # Check answer
                ans_sheet = sheet.worksheet("1-CategoryAnswer")
                all_answers = ans_sheet.get_all_records()
                valid_answers = [str(r['CorrectAnswer']).lower() for r in all_answers if r['CategoryID'] == cat['CategoryID']]

                if user_input.lower() in valid_answers:
                    if user_input.lower() in [x.lower() for x in st.session_state.m1_answers]:
                        st.warning("You already said that!")
                    else:
                        st.session_state.m1_answers.append(user_input)
                        st.rerun()
                else:
                    st.error("Incorrect answer.")
    else:
        st.balloons()
        st.success("Category Complete!")
        if st.button("Finish & Save"):
            save_mode1_session(sheet, cat['CategoryID'], len(st.session_state.m1_answers), st.session_state.m1_answers)
            st.session_state.score += len(st.session_state.m1_answers)
            st.session_state.page = 'menu'
            st.rerun()

def mode2_play(sheet):
    st.title("Guess the Character")
    char_sheet = sheet.worksheet("2-Characters")
    characters = char_sheet.get_all_records()

    if st.session_state.m2_index >= len(characters):
        st.success("You have finished all characters!")
        if st.button("Back to Menu"):
            st.session_state.page = 'menu'
            st.rerun()
        return

    current_char = characters[st.session_state.m2_index]

    # Show Clues based on attempts
    st.subheader("Clues:")
    clues = [current_char['Clue1'], current_char['Clue2'], current_char['Clue3']]

    for i in range(st.session_state.m2_attempts + 1):
        if i < 3:
            st.info(f"🕵️ {clues[i]}")

    with st.form("guess_form", clear_on_submit=True):
        guess = st.text_input("Who is this?")
        submitted = st.form_submit_button("Submit Guess")

        if submitted and guess:
            if guess.lower() == current_char['CharacterName'].lower():
                st.success("Correct!")
                st.session_state.score += 1
                save_mode2_guess(sheet, current_char['CharacterID_Old'], st.session_state.m2_attempts, True, guess)
                # Move to next character
                st.session_state.m2_index += 1
                st.session_state.m2_attempts = 0
                time.sleep(1) # specific pause so user sees "Correct"
                st.rerun()
            else:
                st.error("Wrong!")
                save_mode2_guess(sheet, current_char['CharacterID_Old'], st.session_state.m2_attempts, False, guess)
                if st.session_state.m2_attempts < 2:
                    st.session_state.m2_attempts += 1
                    st.rerun()
                else:
                    st.error(f"Out of clues! The answer was {current_char['CharacterName']}")
                    if st.form_submit_button("Next Character"):
                         st.session_state.m2_index += 1
                         st.session_state.m2_attempts = 0
                         st.rerun()

# --- MAIN ROUTER ---

def main():
    try:
        sheet = connect_to_sheet()
    except Exception as e:
        st.error("Could not connect to Google Sheets. Please check your credentials.")
        st.error(e)
        return

    if st.session_state.page == 'home':
        home_page()
    elif st.session_state.page == 'menu':
        menu_page()
    elif st.session_state.page == 'mode1_select':
        mode1_select(sheet)
    elif st.session_state.page == 'mode1_play':
        mode1_play(sheet)
    elif st.session_state.page == 'mode2_play':
        mode2_play(sheet)

if __name__ == "__main__":
    main()